name: Run Terraform for HomeLab

on:
  workflow_dispatch:
    inputs:
      node:
        description: 'Node to deploy VM to'     
        required: true
        default: 'homelab'

env:
  TF_VAR_proxmox_api_url : ${{ secrets.PROXMOX_API_URL}}
  TF_VAR_proxmox_api_token_id : ${{ secrets.PROXMOX_API_TOKEN_ID }}
  TF_VAR_proxmox_api_token_secret : ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
  TF_LOG : "DEBUG"

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./Terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Export node env var
        run: echo "TF_VAR_homelab_node=${{ github.event.inputs.node}}" >> $GITHUB_ENV

      - name: Echo node env var
        run: echo "homelab node being used is = [ $TF_VAR_homelab_node ]"

      - name: Initialise Terraform
        run: terraform init

      - name: Run Terraform
        run: terraform apply -auto-approve
          

